name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

      - name: Overwrite file
        uses: "DamianReeves/write-file-action@d4ee8a06aec5db0c57a036b86f2f428e1f8b00e7" # master
        with:
          path: ci/test-output/out.js
          write-mode: overwrite
          contents: |
            console.log('some contents: ${{github.ref_name}}')
            
      - name: Commit & Push
        uses: Andro999b/push@c77535fe7a94645f7ceca83e48e6cc977620710e # v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          message: 'Overwritten by Github Actions - ${date}'
